### ISSUE TITLE
whenDev, whenCI is not a function or its return value is not iterable 

### ISSUE THREAD

**Issue by ashishsantikari** [sharegate/craco#107]
I am getting the following error when using when, whenDev and whenCI functions in craco.config.js

```
TypeError: whenDev(...) is not a function or its return value is not iterable
    at Object.<anonymous> (/Users/asantikari/Documents/git/sc-spike/new-cart/craco.config.js:22:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadCracoConfig (/Users/asantikari/Documents/git/sc-spike/new-cart/node_modules/@craco/craco/lib/config.js:48:20)
    at Object.<anonymous> (/Users/asantikari/Documents/git/sc-spike/new-cart/node_modules/@craco/craco/scripts/build.js:16:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My config looks like this.
```
module.exports = {
	webpack: {
  	plugins: [
      ...whenDev(() => [
        new BundleAnalyzerPlugin({
          analyzerMode: 'static',
          reportFilename: '../bundle-stats/report.html',
          openAnalyzer: false,
          logLevel: 'error',
        }),
      ]),
    ],
  }
}
```

CRACO Version: 3.2.3

**Comment by patricklafrance** [comment]
Hi @ashishsantikari 

How do you import `whenDev` ?

Thank you

**Comment by ashishsantikari** [comment]
Hey @patricklafrance 

I imported using require. 

```
const { whenDev } = require('@craco/craco');
```

**Comment by ashishsantikari** [comment]
Is there any updates on this?

**Comment by patricklafrance** [comment]
Hi @ashishsantikari 

Everything seems fine for `whenDev`, do you have a repro case?

As for `whenCI`, sorry I meant to remove it in a previous version but I didn't see it through and the documentation hasn't been updated accordingly. The updated documentation will be release soon.

You can find an alternative here: https://github.com/sharegate/craco/blob/master/changelog/5.5.0.md

Thank you,

Patrick

**Comment by ashishsantikari** [comment]
@patricklafrance I am able to make it work now. It's too complicated to debug problems in craco config.
