### ISSUE TITLE
Forked, scoped react-scripts - test + craco doesn't work

### ISSUE THREAD

**Issue by dstudzinski** [sharegate/craco#52]
I have problem with craco with my custom react-scripts. The problem occurs only in test script

Long story:
I forked create-react-app and created custom react-scripts (to be able to have multiple entry points by ENTRY env variable). It's done and published as scoped package from this branch https://github.com/dstudzinski/create-react-app/tree/feature/custom-react-scripts
I installed my scoped package `@dstudzinski/react-scripts` and added `--react-scripts` param to scripts like:

`"test": "craco test --react-scripts node_modules/@dstudzinski/react-scripts",`

Craco with my custom scripts works but only for `build` and `start` where I inject some additional webpack plugins.
When I try to run `npm run test` Jest starts and I see the menu but it breaks on each test when I try to run tests:
```
 Test suite failed to run

    Cannot find module '/absolutepathtoproject/node_modules/react-scripts/config/paths.js'

      at resolveConfigFilePath (node_modules/@craco/craco/lib/cra.js:7:20)
      at Object.<anonymous> (node_modules/@craco/craco/lib/cra.js:20:26)

```
With single run (not watch mode) it doesn't work too.

When I replace my test script with `"test": "react-scripts test"` everything works as expected (I don't have modifications for Jest so it works without craco)

Do you have any idea what can be source of the problem?

**Comment by dstudzinski** [comment]
Ok I will try to reproduce it and prepare example (like full repo) and let you know about the results

**Comment by dstudzinski** [comment]
Please try to clone this repo `https://github.com/dstudzinski/cracoi52` then `yarn` then `npm run test` and press `a` (sometimes multiple times)

I realized that it can be caused by configuration so I no longer sure it's craco issue or bug in configuration. When I remove jest or babel from `craco.config.js` it works.

**Comment by patricklafrance** [comment]
Closing this issue since there is no activity.

**Comment by dstudzinski** [comment]
Sorry for the delay. I checked with craco 3.5.0 and it works without problems. I updated repo with latest changes. Thank you!
