### ISSUE TITLE
Malformed plugin at index: 1 of 'plugins'.

### ISSUE THREAD

**Issue by hckhanh** [sharegate/craco#68]
I receive this error when I try to build the project:

```
C:\Users\hoang\repos\notesth\node_modules\@craco\craco\lib\config.js:31
                throw new Error(`craco: Malformed plugin at index: ${index} of 'plugins'.`);
                ^

Error: craco: Malformed plugin at index: 1 of 'plugins'.
    at cracoConfig.plugins.forEach (C:\Users\hoang\repos\notesth\node_modules\@craco\craco\lib\config.js:31:23)
    at Array.forEach (<anonymous>)
    at ensureConfigSanity (C:\Users\hoang\repos\notesth\node_modules\@craco\craco\lib\config.js:29:29)
    at loadCracoConfig (C:\Users\hoang\repos\notesth\node_modules\@craco\craco\lib\config.js:57:5)
    at Object.<anonymous> (C:\Users\hoang\repos\notesth\node_modules\@craco\craco\scripts\build.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notesth@0.4.0 build: `craco build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the notesth@0.4.0 build script.
```

**Comment by hckhanh** [comment]
Sorry for my mistake, I have a wrong configuration!

**Comment by Stancobridge** [comment]
I just got this error please what is the configuration u used

**Comment by corpulent** [comment]
@Stancobridge Ill just add this here for others that come across this question.

I had to add the monaco editor webpack plugin to my project to get the syntax highlighting working with autocomplete,  and I also had tailwind setup.  Take a look here https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration-file.  My final configuration looked like this.

```javascript
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')
const path = require('path')

module.exports = {
  module: {
    rules: [{
      test: /\.css$/,
      use: ['style-loader', 'css-loader']
    }, {
      test: /\.ttf$/,
      use: ['file-loader']
    }]
  },
  webpack: {
    plugins: {
      add: [
        new MonacoWebpackPlugin()
      ]
    }
  },
  style: {
    postcss: {
      plugins: [
        require('tailwindcss'),
        require('autoprefixer')
      ],
    },
  },
}
```
